### ISSUE TITLE
Bedrock Custom Form Submint not working

### ISSUE THREAD

**Issue by PalmtreeHD** [crewpvp/skcrew#2]
Hey! First of all: Your addon is really good and everything is working exept for this little "Submint" button in custom forms.

When I press it this error pops up:

[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[05:36:15] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[05:36:15] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[05:36:15] [Server thread/ERROR]: #!#! Following plugins are probably related to this error in some way:
[05:36:15] [Server thread/ERROR]: #!#! Skcrew (https://github.com/LotzyProd/Skcrew) 
[05:36:15] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[05:36:15] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[05:36:15] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[05:36:15] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[05:36:15] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! Stack trace:
[05:36:15] [Server thread/ERROR]: #!#! java.lang.ClassCastException: class org.geysermc.cumulus.component.util.ComponentType cannot be cast to class org.geysermc.cumulus.util.ComponentType (org.geysermc.cumulus.component.util.ComponentType and org.geysermc.cumulus.util.ComponentType are in unnamed module of loader 'floodgate-spigot.jar' @5737b2dd)
[05:36:15] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.floodgate.forms.experssions.ExprFormStepSlider.get(ExprFormStepSlider.java:63)
[05:36:15] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.floodgate.forms.experssions.ExprFormStepSlider.get(ExprFormStepSlider.java:26)
[05:36:15] [Server thread/ERROR]: #!#!     at Skript (26).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[05:36:15] [Server thread/ERROR]: #!#!     at Skript (26).jar//ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:99)
[05:36:15] [Server thread/ERROR]: #!#!     at Skript (26).jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[05:36:15] [Server thread/ERROR]: #!#!     at Skript (26).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[05:36:15] [Server thread/ERROR]: #!#!     at Skript (26).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[05:36:15] [Server thread/ERROR]: #!#!     at Skript (26).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[05:36:15] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.floodgate.forms.sections.SecFormResult.lambda$walk$1(SecFormResult.java:82)
[05:36:15] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.floodgate.forms.Form$1.onSubmit(Form.java:46)
[05:36:15] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.floodgate.forms.FormEvents.onFormSubmit(FormEvents.java:22)
[05:36:15] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor151.execute(Unknown Source)
[05:36:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[05:36:15] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:36:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:36:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[05:36:15] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.floodgate.forms.events.FormListener.lambda$FormListener$2(FormListener.java:41)
[05:36:15] [Server thread/ERROR]: #!#!     at floodgate-spigot.jar//org.geysermc.cumulus.util.glue.CustomFormGlue$Builder.lambda$build$0(CustomFormGlue.java:288)
[05:36:15] [Server thread/ERROR]: #!#!     at floodgate-spigot.jar//org.geysermc.cumulus.form.impl.FormImpl.callRawResponseConsumer(FormImpl.java:56)
[05:36:15] [Server thread/ERROR]: #!#!     at floodgate-spigot.jar//org.geysermc.cumulus.form.impl.FormDefinition.callRawResponseConsumer(FormDefinition.java:69)
[05:36:15] [Server thread/ERROR]: #!#!     at floodgate-spigot.jar//org.geysermc.cumulus.form.impl.FormDefinition.handleFormResponse(FormDefinition.java:60)
[05:36:15] [Server thread/ERROR]: #!#!     at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.channel.FormChannel.callResponseConsumer(FormChannel.java:130)
[05:36:15] [Server thread/ERROR]: #!#!     at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.channel.FormChannel.handleServerCall(FormChannel.java:93)
[05:36:15] [Server thread/ERROR]: #!#!     at floodgate-spigot.jar//org.geysermc.floodgate.pluginmessage.SpigotPluginMessageRegistration.lambda$register$0(SpigotPluginMessageRegistration.java:44)
[05:36:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3160)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:38)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:7)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[05:36:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[05:36:15] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! Version Information:
[05:36:15] [Server thread/ERROR]: #!#!   Skript: 2.6.1
[05:36:15] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[05:36:15] [Server thread/ERROR]: #!#!     Date: 22:18:42.554713200
[05:36:15] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[05:36:15] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[05:36:15] [Server thread/ERROR]: #!#!   Java: 17.0.3 (OpenJDK 64-Bit Server VM 17.0.3+7-Debian-1deb11u1)
[05:36:15] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-1160.53.1.vz7.185.3
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! Server platform: Paper
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! Current node: null
[05:36:15] [Server thread/ERROR]: #!#! Current item: broadcast form slider result
[05:36:15] [Server thread/ERROR]: #!#! Current trigger: form sumbit event (form sumbit event) (begui.sk, line -1)
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! Thread: Server thread
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! Language: english
[05:36:15] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[05:36:15] [Server thread/ERROR]: #!#! 
[05:36:15] [Server thread/ERROR]: #!#! End of Error.
[05:36:15] [Server thread/ERROR]: #!#! 

This is the Code:

command /testform:
	trigger:
		create custom form named "Time":
			label named "§eTime"
			step slider named "Set time to" with elements "Standart","Noon","Midnight"
			label named "§eDay-Light-Cycle"
			toggle named "The Day-Time progresses while the game is running"
			run on form result:
				broadcast step slider 1 value
				broadcast "result"
		open last created form to player

**Comment by Lotzyprod** [comment]
Thank for your issue, I will try to solve this problem as soon as possible

**Comment by PalmtreeHD** [comment]
Trank you

**Comment by Lotzyprod** [comment]
> Thank you

temporarily fixed
