### ISSUE TITLE
PostgreSQL Database: No suitable driver

### ISSUE THREAD

**Issue by Dere-Wah** [crewpvp/skcrew#22]
I am trying to connect to a PostgreSQL database, but when doing so, I am getting the SQLException "No suitable driver".

I am using this syntax:

set {piazza::db} to the database "postgresql://<ip>:<port>/<dbname>?user=<name>&password=<pass>&ssl=false"
 but when I execute any statement on the db this error is printed in console:
 
 ```
 [09:39:51 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:postgresql://MY-IP:PORT/postgres?user=USERNAME&password=<masked>&ssl=false
[09:39:51 INFO]: [Skript] Successfully reloaded db.sk. (49ms)
[09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[09:39:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:39:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:39:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[09:39:51 WARN]: Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:postgresql://MY-IP:PORT/postgres?user=USERNAME&password=<masked>&ssl=false
[09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
[09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
[09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
[09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
[09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
[09:39:51 WARN]:        at Skcrew-patch.jar//com.lotzy.skcrew.spigot.sql.SqlUtil.executeStatement(SqlUtil.java:40)
[09:39:51 WARN]:        at Skcrew-patch.jar//com.lotzy.skcrew.spigot.sql.effects.EffAsyncExecuteStatement.lambda$execute$0(EffAsyncExecuteStatement.java:63)
[09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:39:51 WARN]:        ... 3 more
[09:39:51 WARN]: Caused by: java.sql.SQLException: No suitable driver
[09:39:51 WARN]:        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300)
[09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
[09:39:51 WARN]:        ... 10 more
```

Even after going through the Skript-DB documentation, and seeing this:

![image](https://github.com/user-attachments/assets/45ba220d-c856-4835-82f6-9e20fd3b70af)

I saw that I had to change the default driver to point at a PostgreSQL db driver. From an old issue on skript-db:
https://git.limework.net/Limework/skript-db/issues/14

the solution is shading the Driver directly into the jar. In skript-db this is actually done, but on the releases on this github repo I don't see the Driver in any place.

To test further I tried adding the driver myself in the path org.postgresql.Driver in the Skcrew jar but yet the same error appears when trying to connect to a PostgreSQL.

**Comment by Lotzyprod** [comment]
> I am trying to connect to a PostgreSQL database, but when doing so, I am getting the SQLException "No suitable driver".
> 
> I am using this syntax:
> 
> set {piazza::db} to the database "postgresql://:/?user=&password=&ssl=false" but when I execute any statement on the db this error is printed in console:
> 
> ```
> [09:39:51 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:postgresql://MY-IP:PORT/postgres?user=USERNAME&password=<masked>&ssl=false
> [09:39:51 INFO]: [Skript] Successfully reloaded db.sk. (49ms)
> [09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> [09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> [09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
> [09:39:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [09:39:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [09:39:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
> [09:39:51 WARN]: Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:postgresql://MY-IP:PORT/postgres?user=USERNAME&password=<masked>&ssl=false
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.lotzy.skcrew.spigot.sql.SqlUtil.executeStatement(SqlUtil.java:40)
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.lotzy.skcrew.spigot.sql.effects.EffAsyncExecuteStatement.lambda$execute$0(EffAsyncExecuteStatement.java:63)
> [09:39:51 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
> [09:39:51 WARN]:        ... 3 more
> [09:39:51 WARN]: Caused by: java.sql.SQLException: No suitable driver
> [09:39:51 WARN]:        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300)
> [09:39:51 WARN]:        at Skcrew-patch.jar//com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
> [09:39:51 WARN]:        ... 10 more
> ```
> 
> Even after going through the Skript-DB documentation, and seeing this:
> 
> ![image](https://private-user-images.githubusercontent.com/160314410/348631013-45ba220d-c856-4835-82f6-9e20fd3b70af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzk3MzksIm5iZiI6MTcyMTAzOTQzOSwicGF0aCI6Ii8xNjAzMTQ0MTAvMzQ4NjMxMDEzLTQ1YmEyMjBkLWM4NTYtNDgzNS04MmY2LTllMjBmZDNiNzBhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMDMwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjZiZWY1ZTRiOGYyYmE3MTY5NGQxMDFiNTc5ZDllYmIzOWRlMDY2MWY2ZDE3MTQ1MmQxNTZjZDQyYWM2NWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8crbxqPTtY8lpNjo863ek_PTSucPfpIdwSgiBOhMoM4)
> 
> I saw that I had to change the default driver to point at a PostgreSQL db driver. From an old issue on skript-db: https://git.limework.net/Limework/skript-db/issues/14
> 
> the solution is shading the Driver directly into the jar. In skript-db this is actually done, but on the releases on this github repo I don't see the Driver in any place.
> 
> To test further I tried adding the driver myself in the path org.postgresql.Driver in the Skcrew jar but yet the same error appears when trying to connect to a PostgreSQL.

Yea, thanks for the issue. Added the driver, I'll release it a bit later (there's another problem with the packets module)

**Comment by Dere-Wah** [comment]
Thanks ;D
Just to be clear, adding the driver to the path *did not fix the issue* when I did it on my own, editing the .jar of Skcrew.

**Comment by Lotzyprod** [comment]
Most likely you did everything correctly, the problem was that even the value from the config was read incorrectly. But I fixed everything, now in general, in most cases there is no need to think about the driver, unless of course there is some very specific DBMS



> Thanks ;D Just to be clear, adding the driver to the path _did not fix the issue_ when I did it on my own, editing the .jar of Skcrew.
