### ISSUE TITLE
Failed to load driver class com.mysql.cj.jdbc from HikariConfig class classloader PluginClassLoader

### ISSUE THREAD

**Issue by juzijun233** [crewpvp/skcrew#23]
```
[com.zaxxer.hikari.HikariConfig] Failed to load driver class com.mysql.cj.jdbc from HikariConfig class classloader PluginClassLoader{plugin=Skcrew v3.8, pluginEnabled=true, url=plugins/.paper-remapped/!Skcrew-3.8.jar}
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! [Skript] Severe Error:
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! Something went horribly wrong with Skript.
[14:07:10 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:07:10 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:07:10 ERROR]: #!#! Here is full list of them:
[14:07:10 ERROR]: #!#! skript-placeholders v1.6.0 (https://github.com/APickledWalrus/skript-placeholders) skript-citizens v1.0.0 skript-reflect v2.5.1 (https://github.com/SkriptLang/skript-reflect) SkReloader v1.0.1 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) SkJson v4.0.1 skript-yaml v1.5 SkBee v3.5.9 (https://github.com/ShaneBeee/SkBee) Skcrew v3.8 (https://github.com/crewpvp/skcrew) skript-worldedit v1.1.1 skript-db v1.3.9 
[14:07:10 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:07:10 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:07:10 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:07:10 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:07:10 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:07:10 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! Stack trace:
[14:07:10 ERROR]: #!#! java.lang.RuntimeException: Failed to load driver class com.mysql.cj.jdbc in either of HikariConfig class loader or Thread context classloader
[14:07:10 ERROR]: #!#!     at !Skcrew-3.8.jar//com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491)
[14:07:10 ERROR]: #!#!     at !Skcrew-3.8.jar//com.lotzy.skcrew.spigot.sql.expressions.ExprDataSource.get(ExprDataSource.java:67)
[14:07:10 ERROR]: #!#!     at !Skcrew-3.8.jar//com.lotzy.skcrew.spigot.sql.expressions.ExprDataSource.get(ExprDataSource.java:19)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:97)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.events.EvtScript.postLoad(EvtScript.java:61)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.structures.StructEvent.postLoad(StructEvent.java:91)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$9(ScriptLoader.java:594)
[14:07:10 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1756)
[14:07:10 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1744)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:585)
[14:07:10 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[14:07:10 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[14:07:10 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:513)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[14:07:10 ERROR]: #!#!     at !Skript-2.9.1.jar//ch.njol.skript.Skript$1.run(Skript.java:853)
[14:07:10 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[14:07:10 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[14:07:10 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241)
[14:07:10 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[14:07:10 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! Version Information:
[14:07:10 ERROR]: #!#!   Skript: 2.9.1 (latest)
[14:07:10 ERROR]: #!#!     Flavor: skriptlang-github
[14:07:10 ERROR]: #!#!     Date: 14:17:55.682181900
[14:07:10 ERROR]: #!#!   Bukkit: 1.21.1-R0.1-SNAPSHOT
[14:07:10 ERROR]: #!#!   Minecraft: 1.21.1
[14:07:10 ERROR]: #!#!   Java: 22.0.2 (Java HotSpot(TM) 64-Bit Server VM 22.0.2+9-jvmci-b01)
[14:07:10 ERROR]: #!#!   OS: Linux amd64 6.8.12-1-pve
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! Server platform: Paper
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! Current node: on load: (EndlessMineralDeposits/0.初始化.sk, line 1)
[14:07:10 ERROR]: #!#! Current item: set {-游戏::数据库链接} (as java.lang.Object) to Datasource: "mysql://127.0.0.1:3306/ops_data?user=skript&password=%{_密码} (as java.lang.Object)%&useSSL=false"
[14:07:10 ERROR]: #!#! Current trigger: load (script load) (EndlessMineralDeposits/0.初始化.sk, line 1)
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! Thread: Server thread
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! Language: english
[14:07:10 ERROR]: #!#! Link parse mode: DISABLED
[14:07:10 ERROR]: #!#! 
[14:07:10 ERROR]: #!#! End of Error.
[14:07:10 ERROR]: #!#! 
```

**Comment by Lotzyprod** [comment]
Thanks for the issue, I'll fix that tomorrow

**Comment by Lotzyprod** [comment]
Fixed. Download new release
