### ISSUE TITLE
Incompatibility with skent - Can't register java.nio.file.Path with the code name path because that name is already used by types.path

### ISSUE THREAD

**Issue by LuckyTodays** [crewpvp/skcrew#24]
```
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! [Skript] Severe Error:
[16:37:33 ERROR]: #!#! class com.lotzy.skcrew.spigot.files.types.TypePath generated an exception while loading
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! Something went horribly wrong with Skript.
[16:37:33 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:37:33 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:37:33 ERROR]: #!#! Following plugins are probably related to this error in some way:
[16:37:33 ERROR]: #!#! Skcrew (https://github.com/crewpvp/skcrew)
[16:37:33 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:37:33 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:37:33 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:37:33 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:37:33 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! Stack trace:
[16:37:33 ERROR]: #!#! java.lang.IllegalArgumentException: Can't register java.nio.file.Path with the code name path because that name is already used by types.path
[16:37:33 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:95)
[16:37:33 ERROR]: #!#!     at Skcrew (3).jar//com.lotzy.skcrew.spigot.files.types.TypePath.<clinit>(TypePath.java:13)
[16:37:33 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[16:37:33 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:534)
[16:37:33 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:513)
[16:37:33 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:202)
[16:37:33 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[16:37:33 ERROR]: #!#!     at Skcrew (3).jar//com.lotzy.skcrew.spigot.Config.loadFilesModule(Config.java:216)
[16:37:33 ERROR]: #!#!     at Skcrew (3).jar//com.lotzy.skcrew.spigot.Skcrew.onEnable(Skcrew.java:36)
[16:37:33 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[16:37:33 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[16:37:33 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[16:37:33 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[16:37:33 ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[16:37:33 ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[16:37:33 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[16:37:33 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[16:37:33 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[16:37:33 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[16:37:33 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[16:37:33 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! Version Information:
[16:37:33 ERROR]: #!#!   Skript: 2.9.1 (latest)
[16:37:33 ERROR]: #!#!     Flavor: skriptlang-github
[16:37:33 ERROR]: #!#!     Date: 14:17:55.682181900
[16:37:33 ERROR]: #!#!   Bukkit: 1.21.1-R0.1-SNAPSHOT
[16:37:33 ERROR]: #!#!   Minecraft: 1.21.1
[16:37:33 ERROR]: #!#!   Java: 21.0.3 (Java HotSpot(TM) 64-Bit Server VM 21.0.3+7-LTS-152)
[16:37:33 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! Server platform: Paper
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! Current node: null
[16:37:33 ERROR]: #!#! Current item: null
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! Thread: Server thread
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! Language: english
[16:37:33 ERROR]: #!#! Link parse mode: DISABLED
[16:37:33 ERROR]: #!#!
[16:37:33 ERROR]: #!#! End of Error.
[16:37:33 ERROR]: #!#!
```
paper 1.21.1
skript 2.9.1

error occurs when skcrew and skent are on the server at the same time

pochini eto

**Comment by Lotzyprod** [comment]
поч не отключить бы модуль работы с файлами и жить дальше? 
но бтв окей , починю

**Comment by Lotzyprod** [comment]
исправлено, но опять же лучше отключать модуль в конфиге.

**Comment by LuckyTodays** [comment]
Мне необходимо максимальное удобство 
![1682541355_papik-pro-p-peka-smail-png-27 (2)](https://github.com/user-attachments/assets/bc6ff772-c5c6-4b0f-930f-9466a2ed230f)

**Comment by Lotzyprod** [comment]
ну просто skcrew базируется на skent очень старой версии, когда разраб подзабил хуй на полгода и аддон тупа не работал. Поэтому там 100% один хуй будут конфликты. Лучше отключать модуль в Skcrew и использовать Skent, имхо там есть асинхронная работа с файлами.
